### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Sacred-Shadow** [Linkolas/RW_Stabilize#1]
Hey @Linkolas, 

i have the text for you. :)

`<StabilizePawn>Stabilisiere {1_label}</StabilizePawn>`

**Comment by Linkolas** [comment]
Hey @Sacred-Shadow 
Thank you!

There is actually 2 lines to translate. You can take a look at what have been done for the Japanese translation: https://github.com/Linkolas/RW_Stabilize/tree/master/1.1/Languages/Japanese 

Here is the missing line to translate: "stabilizing TargetA." 
This line shows at the lower left part of the srceen, where you can read what a selected pawn is doing.

**Comment by Sacred-Shadow** [comment]
Okay, tried it once. Hope I served Git correctly. : D
#2

**Comment by Linkolas** [comment]
Merged! Thank you, great work ;)
